POST http://localhost:3000/api/v1/customer/register
Content-Type: application/json

{
    "fname": "Marjorie",
    "lname": "Chan",
    "email": "machan@ateneo.edu",
    "pw": "hashedPassword"
}

###
POST http://localhost:3000/api/v1/customer/login
Content-Type: application/json

{
    "email": "machan@ateneo.edu",
    "pw": "hashedPassword"
}
###
DELETE http://localhost:3000/api/v1/logout
Content-Type: application/json

{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hY2hhbkBhdGVuZW8uZWR1IiwiaWF0IjoxNTk0MDMxMzk3fQ.4vZKCV3pwcc0T2kLqLi2BvQbrXf4mNsVuWgrmoReSiA"}

###
POST http://localhost:3000/api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmpvcmllYWNoYW5AZ21haWwuY29tIiwiaWF0IjoxNTk0MjE0NTgyLCJleHAiOjE1OTQyMTUxODJ9.XzeWSI0e3Q0dRlcei2cLy3yXzFzIwLjmRPgZzHUkOgs

{
    "phone": "9335718905"
}

###
GET https://jasminechan.xyz:3001/api/v1/products

###
GET http://localhost:3000/api/v1/ordersAdmin
?o.order_status=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hY2hhbkBhdGVuZW8uZWR1IiwiaWF0IjoxNTk0MDMzODM0LCJleHAiOjE1OTQwMzQ0MzR9.iSj7RnI9FHONkza2y6-sxuebR-AB8pvYHW8P9HiGZpU

###
GET http://localhost:3000/api/v1/cart

###
POST http://localhost:3000/api/v1/postProduct
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmpvcmllYWNoYW5AZ21haWwuY29tIiwiaWF0IjoxNTk0MjIwMzcwLCJleHAiOjE1OTQyMjA5NzB9.ZZrOlUSVmtOHRy6t8McPQbTAXpn1CqpivZFk1z-Ioy8


{
    "product_name": "soap",
    "descrip": "squeaky clean",
    "price": 10,
    "stock": 500,
    "cat_id": 3
}

###
DELETE http://localhost:3000/api/v1/deleteProduct
?product_name=ham
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hY2hhbkBhdGVuZW8uZWR1IiwiaWF0IjoxNTk0MDM4ODkyLCJleHAiOjE1OTQwMzk0OTJ9.tMrgfSuzfvlQ3EH6VKSHwUWjsF-seyrf548WAL_RALE

###
GET http://localhost:3000/api/v1/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hY2hhbkBhdGVuZW8uZWR1IiwiaWF0IjoxNTk0MDMzNjk2fQ.6EEdp-qZTxY93INxIHkZeK2x2ahKT4aiR5pZVPmQ0j4

###
DELETE http://localhost:3000/api/v1/deleteProduct
?product_name=ham
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hY2hhbkBhdGVuZW8uZWR1IiwiaWF0IjoxNTk0MDM5NTYxLCJleHAiOjE1OTQwNDAxNjF9.I8FOFKPmV2N0gsFXmmfnTj8dXUEd0yFne_IGjwDF_t0

###
POST http://localhost:3000/api/v1/refresh
Content-Type: application/json

###
POST http://localhost:3000/api/v1/admin/login
Content-Type: application/json

{
    "email": "machan@ateneo.edu",
    "pw": "hashedPassword"
}

### 

POST http://localhost:3000/api/v1/admin/register
Content-Type: application/json

{
    "email": "machan@ateneo.edu",
    "pw": "hashedPassword"
}

###
POST http://localhost:3000/api/v1/postOrder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmpvcmllYWNoYW5AZ21haWwuY29tIiwiaWF0IjoxNTk0MjIwMzcwLCJleHAiOjE1OTQyMjA5NzB9.ZZrOlUSVmtOHRy6t8McPQbTAXpn1CqpivZFk1z-Ioy8

{
    "payment_method": "GCash",
    "address": "Juan Luna"
}

###
POST http://localhost:3000/api/v1/addtoCart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmpvcmllYWNoYW5AZ21haWwuY29tIiwiaWF0IjoxNTk0MjIwMzcwLCJleHAiOjE1OTQyMjA5NzB9.ZZrOlUSVmtOHRy6t8McPQbTAXpn1CqpivZFk1z-Ioy8

{
    "product_id": 6,
    "qty": 1
}

###
POST http://localhost:3000/api/v1/updateProduct
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hY2hhbkBhdGVuZW8uZWR1IiwiaWF0IjoxNTk0MjIzMzI0LCJleHAiOjE1OTQyMjM5MjR9.Qoame30D66BXUNSrferIIlbUqHMm3TwKNIS31jYddpw

{
    "product_id": 1,
    "img": "https://i1.wp.com/www.eatthis.com/wp-content/uploads/2017/10/dark-chocolate-bar-squares.jpg?fit=1024%2C750&ssl=1"
}

###
GET http://localhost:3000/api/v1/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hY2hhbkBhdGVuZW8uZWR1IiwiaWF0IjoxNTk0MjEzNDgzLCJleHAiOjE1OTQyMTQwODN9.b6igFtEqBE4ug4245u9jAgxW8PSLuVw-y07iRot4NR0

###
POST https://jasminechan.xyz:3001/api/v1/register

{
    "fname": "Mae",
    "lname": "Co",
    "email": "maeco@gmail.com",
    "pw": "asdf"
}